export const parseAsciiNum = (word: string) =>
    word
        .replaceAll('_0', 'a')
        .replaceAll('_1', 'e')
        .replaceAll('_2', 'q')
        .replaceAll('_3', 'i')
        .replaceAll('_4', 'w')
        .replaceAll('_5', 'o')
        .replaceAll('_6', 'u')
        .replaceAll('_7', 'y')
        .replaceAll('0', 'b')
        .replaceAll('1', 'p')
        .replaceAll('2', 'm')
        .replaceAll('3', 'f')
        .replaceAll('4', 'd')
        .replaceAll('5', 't')
        .replaceAll('6', 'n')
        .replaceAll('7', 'l')
        .replaceAll('8', 'z')
        .replaceAll('9', 'c')
        .replaceAll('A', 's')
        .replaceAll('B', 'g')
        .replaceAll('C', 'k')
        .replaceAll('D', 'h')
        .replaceAll('E', 'j')
        .replaceAll('F', 'r');

export const toAsciiNum = (word: string) =>
    word
        .replaceAll('a', '_0')
        .replaceAll('e', '_1')
        .replaceAll('q', '_2')
        .replaceAll('i', '_3')
        .replaceAll('w', '_4')
        .replaceAll('o', '_5')
        .replaceAll('u', '_6')
        .replaceAll('y', '_7')
        .replaceAll('b', '0')
        .replaceAll('p', '1')
        .replaceAll('m', '2')
        .replaceAll('f', '3')
        .replaceAll('d', '4')
        .replaceAll('t', '5')
        .replaceAll('n', '6')
        .replaceAll('l', '7')
        .replaceAll('z', '8')
        .replaceAll('c', '9')
        .replaceAll('s', 'A')
        .replaceAll('g', 'B')
        .replaceAll('k', 'C')
        .replaceAll('h', 'D')
        .replaceAll('j', 'E')
        .replaceAll('r', 'F');
