export const parseAsciiNum = (word: string) =>
    word
        .replace(/_0/g, 'a')
        .replace(/_1/g, 'e')
        .replace(/_2/g, 'q')
        .replace(/_3/g, 'i')
        .replace(/_4/g, 'w')
        .replace(/_5/g, 'o')
        .replace(/_6/g, 'u')
        .replace(/_7/g, 'y')
        .replace(/0/g, 'b')
        .replace(/1/g, 'p')
        .replace(/2/g, 'm')
        .replace(/3/g, 'f')
        .replace(/4/g, 'd')
        .replace(/5/g, 't')
        .replace(/6/g, 'n')
        .replace(/7/g, 'l')
        .replace(/8/g, 'z')
        .replace(/9/g, 'c')
        .replace(/A/g, 's')
        .replace(/B/g, 'g')
        .replace(/C/g, 'k')
        .replace(/D/g, 'h')
        .replace(/E/g, 'j')
        .replace(/F/g, 'r');

export const toAsciiNum = (word: string) =>
    word
        .replace(/a/g, '_0')
        .replace(/e/g, '_1')
        .replace(/q/g, '_2')
        .replace(/i/g, '_3')
        .replace(/w/g, '_4')
        .replace(/o/g, '_5')
        .replace(/u/g, '_6')
        .replace(/y/g, '_7')
        .replace(/b/g, '0')
        .replace(/p/g, '1')
        .replace(/m/g, '2')
        .replace(/f/g, '3')
        .replace(/d/g, '4')
        .replace(/t/g, '5')
        .replace(/n/g, '6')
        .replace(/l/g, '7')
        .replace(/z/g, '8')
        .replace(/c/g, '9')
        .replace(/s/g, 'A')
        .replace(/g/g, 'B')
        .replace(/k/g, 'C')
        .replace(/h/g, 'D')
        .replace(/j/g, 'E')
        .replace(/r/g, 'F');
