export const parseNum = (word: string) =>
    word
        .replace(/0̅/g, 'a')
        .replace(/1̅/g, 'e')
        .replace(/2̅/g, 'q')
        .replace(/3̅/g, 'i')
        .replace(/4̅/g, 'w')
        .replace(/5̅/g, 'o')
        .replace(/6̅/g, 'u')
        .replace(/7̅/g, 'y')
        .replace(/0/g, 'b')
        .replace(/1/g, 'p')
        .replace(/2/g, 'm')
        .replace(/3/g, 'f')
        .replace(/4/g, 'd')
        .replace(/5/g, 't')
        .replace(/6/g, 'n')
        .replace(/7/g, 'l')
        .replace(/8/g, 'z')
        .replace(/9/g, 'c')
        .replace(/A/g, 's')
        .replace(/B/g, 'g')
        .replace(/C/g, 'k')
        .replace(/D/g, 'h')
        .replace(/E/g, 'j')
        .replace(/F/g, 'r');

export const toNum = (word: string) =>
    word
        .replace(/a/g, '0̅')
        .replace(/e/g, '1̅')
        .replace(/q/g, '2̅')
        .replace(/i/g, '3̅')
        .replace(/w/g, '4̅')
        .replace(/o/g, '5̅')
        .replace(/u/g, '6̅')
        .replace(/y/g, '7̅')
        .replace(/b/g, '0')
        .replace(/p/g, '1')
        .replace(/m/g, '2')
        .replace(/f/g, '3')
        .replace(/d/g, '4')
        .replace(/t/g, '5')
        .replace(/n/g, '6')
        .replace(/l/g, '7')
        .replace(/z/g, '8')
        .replace(/c/g, '9')
        .replace(/s/g, 'A')
        .replace(/g/g, 'B')
        .replace(/k/g, 'C')
        .replace(/h/g, 'D')
        .replace(/j/g, 'E')
        .replace(/r/g, 'F');
