export const parseNum = (word: string) =>
    word
        .replaceAll('0̅', 'a')
        .replaceAll('1̅', 'e')
        .replaceAll('2̅', 'q')
        .replaceAll('3̅', 'i')
        .replaceAll('4̅', 'w')
        .replaceAll('5̅', 'o')
        .replaceAll('6̅', 'u')
        .replaceAll('7̅', 'y')
        .replaceAll('0', 'b')
        .replaceAll('1', 'p')
        .replaceAll('2', 'm')
        .replaceAll('3', 'f')
        .replaceAll('4', 'd')
        .replaceAll('5', 't')
        .replaceAll('6', 'n')
        .replaceAll('7', 'l')
        .replaceAll('8', 'z')
        .replaceAll('9', 'c')
        .replaceAll('A', 's')
        .replaceAll('B', 'g')
        .replaceAll('C', 'k')
        .replaceAll('D', 'h')
        .replaceAll('E', 'j')
        .replaceAll('F', 'r');

export const toNum = (word: string) =>
    word
        .replaceAll('a', '0̅')
        .replaceAll('e', '1̅')
        .replaceAll('q', '2̅')
        .replaceAll('i', '3̅')
        .replaceAll('w', '4̅')
        .replaceAll('o', '5̅')
        .replaceAll('u', '6̅')
        .replaceAll('y', '7̅')
        .replaceAll('b', '0')
        .replaceAll('p', '1')
        .replaceAll('m', '2')
        .replaceAll('f', '3')
        .replaceAll('d', '4')
        .replaceAll('t', '5')
        .replaceAll('n', '6')
        .replaceAll('l', '7')
        .replaceAll('z', '8')
        .replaceAll('c', '9')
        .replaceAll('s', 'A')
        .replaceAll('g', 'B')
        .replaceAll('k', 'C')
        .replaceAll('h', 'D')
        .replaceAll('j', 'E')
        .replaceAll('r', 'F');
